version: '3.4'

services:
  shippingservice.api:
    image: ${DOCKER_REGISTRY-}shippingserviceapi
    container_name: shipping-service-api
    build:
      context: .
      dockerfile: ShippingService.Api/Dockerfile
    depends_on:
        - database

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    environment:
        SA_PASSWORD: "Abcd1234!"
        ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - ./mssql/data:/var/opt/mssql/data
      - ./mssql/log:/var/opt/mssql/log
      - ./mssql/secrets:/var/opt/mssql/secrets